# @url = http://localhost:2026/api/
@cid = 60858a3dbf27ce642cb6822c
@mid = 64cf7d954116fa3fd480844b

get {{url-26}}/api/customers
###

get http://localhost:2026/api/customers
###

get {{url-26-cust}}
###

patch {{url-26}}/api/customers/{{cid}}/method-info/{{mid}}
Content-Type: application/json

{
  "methodName": "Cyberark",
  "url": "http://url.shop",
  "notes": "some notes2 22",
  "username": "user22",
  "password": "pass22"
}
###
post {{url-26}}/api/customers/{{cid}}/method-info
Content-Type: application/json

{
  "methodName": "Cyberark 33",
  "url": "http://url.it",
  "notes": "some notes2 22"
}